/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


// <editor-fold defaultstate="collapsed" desc="Title">
//     Buch: -   plm Java 
//  Kapitel: -   14 - Animationen und Threads
//
//    Thema: -   14.2 - Zeitlich gesteuerte Abläufe programmieren
//
//  Listing: -   14.1 - JAmpelPanel.java
//  
//   NetBeans Project
//
//    Autor: - Daniel dgtl
// </editor-fold> 

// import:

package chpt07.gui14;

import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JPanel;


public class JAmpelPanel extends JPanel {

    int phase = 0;
    Color coben, cmitte, cunten;
    
    /**
     * Creates new form JAmpelPanel
     */
    public JAmpelPanel() {  // public by NetBeans
        super();
        initComponents();  // NB generated
    }
    
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        setBackground(new Color(0,80,0));
        switch (phase) {
        case 0:
            coben = Color.gray;
            cmitte = Color.gray;
            cunten = Color.gray;
            break;
        case 1:
            coben = Color.red;
            cmitte = Color.gray;
            cunten = Color.gray;
            break;
        case 2:
            coben = Color.red;
            cmitte = Color.orange;
            cunten = Color.gray;
            break;
        case 3:
            coben = Color.gray;
            cmitte = Color.gray;
            cunten = Color.green;
            break;
        case 4:
            coben = Color.gray;
            cmitte = Color.orange;
            cunten = Color.gray;
            break;
        }
        int h=getHeight()/3-12;
        int b=getWidth()-6;
        g.setColor(coben);
        g.fillOval(3, 3, b, h);
        g.setColor(cmitte);
        g.fillOval(3, getHeight()/3+6, b, h);
        g.setColor(cunten);
        g.fillOval(3, 2*getHeight()/3+9, b, h);
        g.setColor(Color.black);
        g.drawOval(3, 3, b, h);
        g.drawOval(3, getHeight()/3+6, b, h);
        g.drawOval(3, 2*getHeight()/3+9, b, h);
    } 
    
    public void setPhase(int i) {
        phase=i;
        repaint();
    }
    
    // Ende von 14.1 JAmpelPanel.java
    
    // NB generated
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
