/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

// <editor-fold defaultstate="collapsed" desc="Title">
//     Buch: -   plm Java 
//  Kapitel: -   14 - Animationen und Threads
//
//    Thema: -   14.2 - Zeitlich gesteuerte Abläufe programmieren
//               14.2.4 Bewegungsabläufe programmieren (Synchronisation)
//
//  Listing: -   14.10 - JBallPanel.java  
//  
//   NetBeans Project
//
//    Autor: - Daniel dgtl
// </editor-fold> 

// import:

package chpt07.gui14;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URL;

import javax.imageio.ImageIO;
import javax.swing.JPanel;

public class JBallPanel extends JPanel implements Runnable {
    // zusätzliche Variablen
    // My Variables declaration 
    private int x = 0;
    private Image img;
    private boolean vor = true;

    /**
     * Creates new form JBallPanel
     */
    public JBallPanel() {
        initComponents();
        setBackground(Color.white);
	img = Toolkit.getDefaultToolkit().getImage(
		"." + File.separator + "Ball.jpg");
        /* Alternative ohne Toolkit, die das Bild aus dem bin-Verzeichnis des Package lädt. Dadurch kann
         * das Bild auch in ein jar-File eingebunden werden und muss nicht als separate Datei
         * mit dem jar-File mitgeliefert werden.	
	try {
	    img = ImageIO.read(this.getClass().getResource("Ball.jpg"));
	} catch (IOException e) {
	    // TODO Auto-generated catch block
	    e.printStackTrace();
	}*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // 14.13 run()-Methode zur Aktualisierung der x-Koordinate
    @Override
    public void run() {
        while (true) {
	    synchronized (this) {
		if (x > getWidth() - img.getWidth(this)) {
		    vor = false;
		} else if (x <= 0)
		    vor = true;
		if (vor) {
		    x += 2;
		} else {
		    x -= 2;
		}
	    }
	    repaint();
	    try {
		Thread.sleep(20);
	    } catch (InterruptedException e) {
		break;
	    }
	}
    }
    
    public synchronized void paintComponent(Graphics g) {
	super.paintComponent(g);
	g.drawImage(img, x, getHeight() / 2 - img.getHeight(this) / 2,
		img.getWidth(this), img.getHeight(this), this);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
